name: CI on robotics

on:
  push:
    paths:
      - 'src/**'
    # branches: [ '*' ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          # profile: minimal
          components: rustfmt, clippy
          toolchain: stable
          # override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo static analysis
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -D warnings

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test